### PR TITLE
Ruby/difference-of-squares Update with Integer#pow

### PR DESCRIPTION
**Pull request by F3PiX**
TIL: Since Ruby 2.5 we have Integer#pow!

### CODE REVIEW

**Comment by boddhisattva** [comment]
@F3PiX Thanks for adding another alternative (`pow(2)`) that can be used as part of this exercise 👍 . I didn't know about this new function earlier.

I'm just curious is there any specific reason why one would prefer `abs2` or `pow(2)` over `**2`. I honestly don't have a strong reason to prefer `abs2` or `pow(2)`  over the `**2` option and thereby all 3 options look valid to me. I'm curious to learn why one would prefer `abs2` or `pow(2)` over `**2` so that this could also serve as a potential reason that we could give to students as well when they do this exercise using `**2`.

**Comment by F3PiX** [comment]
Interesting question. Actually, I like `**2` slightly better than both `abs2` and `pow(2)`.   
- What I like about `pow(2)` is that it signals the need to stay up-to-date with new Ruby versions. Does it matter that it's in `Integer`, where `abs2` comes from `Math`? I don't know.
But, isn't it the worst name ever? That's a reason _not_ to use it :-) 
- One reason why I do like that `abs2` is featured in the Reasonable Solution is to highlight the clean `sym.to_proc` syntax.  

What's your proposal? Should we change the talking points to:
- `**2` `abs2` and `pow(2)` are equally appropriate; boiles down to personal taste. 
?

**Comment by kotp** [comment]
I think the focus should be more on "know what is available to use" because if you don't review the methods occasionally, you won't know that there is something made available.  The suitability is going to be learned over time, the acceptance as well.  This is regardless for my distaste for either method name.

**Comment by iHiD** [comment]
From reading the source code, `pow(2)` does a check, then defers to `**`, so is slower than just using `**`. `**` is also much more complex than `abs2`, as it has more possibilities. So `abs2` will definitely be fastest, then `**`, then finally `pow`. 

I think the key thing to understand is that they are **not** equivalent functions, but are being used to have equivalent outputs in this scenario. `abs2` is **the** method for what we're trying to achieve, but it might be more useful to learn `**` or `pow` for other scenarios.

You can read the code here by clicking the "toggle source" button here:
- [pow](https://ruby-doc.org/core-2.5.1/Integer.html#method-i-pow)
- [**](https://ruby-doc.org/core-2.5.1/Integer.html#method-i-2A-2A)
- [abs2](https://ruby-doc.org/core-2.5.0/Numeric.html#method-i-abs2)

**Comment by boddhisattva** [comment]
Thank you for sharing more insights on each of the functions - `pow`, `**` and `abs2` @iHiD 👍 . Appreciate your sharing the approach you took as well to do the additional research.

@F3PiX Thanks for making additional changes based on our latest discussion. You may want to consider making one last change in the order based on the suggestion by Jeremy to have them in the order - `abs2`, `** 2` or `pow(2)` instead of `** 2`, `abs2` or `pow(2)` . Thank you.

**Comment by F3PiX** [comment]
I'm merging this now :-) We can make changes later if need to.

**Comment by boddhisattva** [comment]
Sure @F3PiX :) 👍

**Pull request merged**
