### PR TITLE
Add some notes on mentoring the Hamming exercise

### PR DESCRIPTION
**Pull request by JoelQ**
I've mentored this exercise more than any other so I have a ton of notes on it. I've unified and condensed them down here but this is still pretty long. Not sure if this is more detailed than what you're looking for 😃

### CODE REVIEW

**Comment by F3PiX** [comment]
Wow! This is a fantastic recording of your mentoring experience. I feel we need to keep this, and I also think it has a level of detail that is beyond a quick reference guide. 
There are some real pearls in it; I witnessed live your mentoring with the part where you describe the pattern with the counter, and pointing to Enumerable methods. And then _challenge_ them to eliminate the counter.  It's such a great explanation of why Enumerables exist in the first place, and then topped of with a challenge. 

One of the issues with the Hamming exercise I see, is that it is the first Enumerable option in the core exercises. I would really like to add a basic Enumerable iteration exercise  _before_ Hamming. That is relevant to your notes, because I feel that Hamming mentoring _should_ be about what Enumerables have to offer beyond `each`, `each_with_index` or inject, like `count` and especially `zip`.

So, for the Hamming exercise I find your notes on the advanced enumerables also very valuable.
But, most solutions in practice require attention for the basic iterators. 
How would you feel about starting the 'Common Suggestions' section with a  few bullet pointed remarks (for easy lookup and reference) that describes the 'mentoring flow' ? 
Something like:
- if first iteration ` .each` => focus mentoring on getting the basic iterations right 
- if first iteration `.each with index ` =>  focus mentoring on getting to advanced enumerables

I think that would meet the first goal of this readme's, to offer a quick reference for other mentors. 

And as a closing points, I myself am struggling if I should share my personal notes / comment snippets, or not. I chose not to. But I am open to a different approach.  It would be interesting to hear more opinions.

But, yeah, that goes for all of the above. :-)

And reading the notes, I realized you influenced a lot of my opinions on Hamming ;-) Thanks for that. 
And a _huge_ thanks for you willing to share this with everyone. 😍

**Comment by JoelQ** [comment]
@F3PiX thanks for your feedback!

> I feel we need to keep this, and I also think it has a level of detail that is beyond a quick reference guide

Do you think I should remove some parts? Move them somewhere else? Perhaps just cut down on the _why_ and focus on the _what_?

> One of the issues with the Hamming exercise I see, is that it is the first Enumerable option in the core exercises. I would really like to add a basic Enumerable iteration exercise before Hamming.

Agreed! 💯 It's definitely a tricker problem to solve if you haven't done any looping in Ruby before. 

Coming up with a good exercise is difficult though. IMO, you almost never want to use `for`/`while`/`until` and even `#each` has limited use unless you're doing side effects. My most common use of `#each` tends to be in ERB templates 😂 . 

> How would you feel about starting the 'Common Suggestions' section with a few bullet pointed remarks (for easy lookup and reference) that describes the 'mentoring flow' ?

I like the idea! I've been thinking about how I mentor this exercise and you've helped me realize that I actually have a pretty linear flow. I've pushed up a new commit describing the flow.

> And as a closing points, I myself am struggling if I should share my personal notes / comment snippets, or not. I chose not to.

Yeah, I wasn't sure either 😅 . The snippet can be a helpful example or reference but I imagine mentors don't want to copy/paste someone else's snippets. I'm happy to remove it if you think that's a good idea.

**Comment by iHiD** [comment]
Love this discussion. Thanks, both.

I'm going to merge this (because it's brilliant and I want to be able to use it **now**) and then we can all PR further suggestions and open issues for discussions as required :)

**Comment by F3PiX** [comment]
Love the new Mentoring Flow, @JoelQ !! Thank you.

**Pull request merged**
