### PR TITLE
Add mentor notes for word-count in Elixir

### PR DESCRIPTION
**Pull request by angelikatyborska**

### CODE REVIEW

**Comment by NobbZ** [comment]
I'm a big fan of “split first” when it comes to processing of binaries, as processing many small binaries might take some stress from the allocator.

Remember, if you have the bible and want to change a single letter, the full bible has to get copied by the runtime to do so.

**Comment by angelikatyborska** [comment]
@NobbZ I assume your comment refers to my proposed solution. Can you help me prove your claim?  I wrote a benchmark but it proves exactly the opposite - doing "split first" is slightly slower and uses slightly more memory. Here is the benchmark, including the result I got as a comment: https://gist.github.com/angelikatyborska/8e77a2a18831d52f878b85ac68e17d0a

Did I do something wrong in the benchmark?

**Comment by NobbZ** [comment]
Interesting.

To be honest, the last time I did the benchmark was ad-hoc, not using benchee or similar tools, and it was in the range of OTP 17 or 18, things might have changed since then.

Another major difference I see is the size of the input. I used a concatenation of many text files, summing up to a couple of megabytes. Not the less than 100 kilobytes in your benchmark.

I've no elixir machine at hands to verify though.

**Comment by Cohen-Carlisle** [comment]
I personally prefer an approach using `Regex.scan`. However, I just realized my solution does not trim trailing dashes. On the other hand, there's no requirement for that currently.
https://exercism.io/tracks/elixir/exercises/word-count/solutions/2853ccc3593947e494d8c422433985d9

**Comment by NobbZ** [comment]
Of course a `Regex.scan/2` is the ultimate answer ;) But during v1, I've learned that most people have a lot more problems to come up with the necessary regex, while the one to split at after normalizing is easier for most of them…

I've observed this across languages.

**Comment by Cohen-Carlisle** [comment]
Note: implements https://github.com/exercism/exercism.io/issues/4140 for elixir/word-count.

**Comment by Cohen-Carlisle** [comment]
This looks good. We can always add more in additional PRs. :tada:

**Pull request merged**
